

export const sample_products : any[] = [
  {
    id:'1',
    name:'Lee Valley Mid-Length Garden Tool Sets',
    price:80,
    favorite:false,
    stars:3.0,
    imageUrl:'assets/img/garden1.jpeg',
    matter:['Iron','Wood'],
    tags:['Gardening'],
  },
  {
    id:'2',
    name:'GardenHOME 10 Piece Garden Tool Set',
    price:50,
    favorite:true,
    stars:4.0,
    imageUrl:'assets/img/garden2.jpeg',
    matter:['Plastic','Wood'],
    tags:['Gardening'],
  },
  {
    id:'3',
    name:'Fiskars Garden Tool Set, 3-Piece',
    price:60,
    favorite:false,
    stars:5.0,
    imageUrl:'assets/img/garden3.jpeg',
    matter:['Iron','Wood'],
    tags:['Gardening'],
  },
  {
    id:'4',
    name:'10 Best Home Gardening Tool Kits',
    price:180,
    favorite:false,
    stars:4.0,
    imageUrl:'assets/img/garden4.jpeg',
    matter:['Iron','Wood'],
    tags:['Gardening'],
  },
  {
    id:'5',
    name:'10 Best Home Gardening Tool Kits',
    price:100,
    favorite:true,
    stars:5.0,
    imageUrl:'assets/img/garden5.jpeg',
    matter:['Iron','Wood'],
    tags:['Gardening','Sol'],
  },
  {
    id:'6',
    name:'4-Piece Garden Hand Tool Set - Cate',
    price:120,
    favorite:false,
    stars:4.0,
    imageUrl:'assets/img/garden6.jpeg',
    matter:['Wood'],
    tags:['Sol'],
  },
  {
    id:'7',
    name:'Yardsmith YS 4-PC WD HAND TOOL SET',
    price:40,
    favorite:false,
    stars:2.0,
    imageUrl:'assets/img/garden7.jpg',
    matter:['Iron','Wood'],
    tags:['Sol','Flower'],
  },
  {
    id:'8',
    name:'20 Of The Best Garden Tools For 2021',
    price:60,
    favorite:false,
    stars:5.0,
    imageUrl:'assets/img/garden8.jpeg',
    matter:['Iron','Wood'],
    tags:['Water'],
  },
  {
    id:'9',
    name:'Garden Tools Set - 8 Piece Heavy Duty',
    price:80,
    favorite:false,
    stars:3.0,
    imageUrl:'assets/img/garden1.jpeg',
    matter:['Iron','Wood'],
    tags:['Gardening','Flower'],
  },
]

export const  sample_tags : any[] = [
  {name: 'Park',count:3},
  {name: 'Sol' ,count : 5},
  {name: 'Gardening' ,count : 8},
  {name: 'Water' ,count : 6},
  {name: 'Flower' ,count : 12},
  {name: 'Accessory' ,count : 2},
  {name: 'Herb' ,count : 9},
  {name: 'Plant' ,count : 1},

]
export const  sample_users : any[] =[
  {
    name: "john Doe",
    email : "john@gmail.com",
    password :"12345",
    address: "Toronto",
    isAdmin : true,
  },
  {
    name: "jane Doe",
    email : "jane@gmail.com",
    password :"0000",
    address: "New York",
    isAdmin : false,
  }
];